# 捕获异常

*项目：exception-catch*

​	捕获异常使用`try...catch`语句，把可能发生异常的代码放到`try{...}`中，然后使用`catch`捕获对应的`Exception`及其子类。

## 多catch语句

​	可以使用多个`catch`语句，每个`catch`分别捕获对应的`Excepion`及其子类。JVM在捕获到异常后，会从上到下匹配`catch`语句，直到匹配上之后就不再继续匹配。

​	因此存在多个`catch`的时候，其顺序非常重要：子类必须写在前面，不然子类会一直被父类截胡。

```java
try {
  //可能出现异常的语句
} [catch (异常类型 异常对象) {
  //异常处理
} catch (异常类型 异常对象) {
  //异常处理
} catch (异常类型 异常对象) {
  //异常处理
} ... ][finally {
  //不管异常是否处理都执行
}]
```





## finally语句

​	无论是否有异常发生，有些工作都是必须执行的。这种情况下我们就需要用`finally`关键字。

​	`finally`语句块保证有无错误都会执行。	

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("程序开始执行");
        try {
            System.out.println("开始计算 1 / 0 = " + (1 / 0));
        } catch (ArithmeticException e) {
            e.printStackTrace();
        } finally {
            System.out.println("不管是否异常，都会执行");
        }
        System.out.println("程序结束执行");
    }
}
```

​	finally语句不是必须的，可写可不写，但是写的话一定放在最后。



## 捕获多种异常

​	如果某些异常的处理逻辑相同，但是异常本身不存在继承关系，那么就得编写多条`catch`子句：

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("Bad input");
    } catch (NumberFormatException e) {
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```

因为处理`IOException`和`NumberFormatException`的代码是相同的，所以我们可以把它两用`|`合并到一起：

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException | NumberFormatException e) {
        // IOException或NumberFormatException
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```